require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
--require "user.autopairs"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggle_term"
require "user.lsp"
require "user.vimtex"
require "user.lualine"
require "user.auto_session"
require "user.markdown_preview"
-- require "user.lsp"
